name: ml-supermatrix-tree
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - snakemake-minimal=7.12.0
  - tabulate=0.8.10
  - pandas=1.4.3
  - mamba=0.27.0
  - pygments=2.13.0
  - pyyaml=6.0
